### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by Max13** [mercuryseries/laravel-elixir-minify-html#1]
Hi there, I saw your elixir extension on laracasts and I wanted to give it a try.

Here is my call:

``` javascript
elixir(function(mix) {
    mix.html('storage/framework/views/*');
});
```

Here is the output:

```
➜  www git:(master) ✗ gulp
[19:10:56] Using gulpfile ~/Dev/OsteApp/www/gulpfile.js
[19:10:56] Starting 'default'...
[19:10:56] Starting 'minify'...
[19:10:56] Finished 'default' after 15 ms

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Parse Error: <f.childNodes.length;h++){h+=a(f.childNodes[h],k)}}}return n}return this.each(function(){a(this,c)})};jQuery.fn.removeHighlight=function(){return this.find("span.highlight").each(function(){this.parentNode.firstChild.nodeName;with(this.parentNode){replaceChild(this.firstChild,this);normalize()}}).end()};

(function () {
    var search = '  en40cq70jmlb2xy2kc3rqkt939  ';

   if ($('table > tbody > tr').length > 0 && search.length > 1) {
        $('table > tbody > tr').highlight(search);
    }
})();   en40cq70jmlb2xy2kc3rqkt940      en40cq70jmlb2xy2kc3rqkt941      en40cq70jmlb2xy2kc3rqkt942  
    at new HTMLParser (/Users/Max13/Dev/OsteApp/www/node_modules/html-minifier/src/htmlparser.js:236:13)
    at minify (/Users/Max13/Dev/OsteApp/www/node_modules/html-minifier/src/htmlminifier.js:913:3)
    at Object.exports.minify (/Users/Max13/Dev/OsteApp/www/node_modules/html-minifier/src/htmlminifier.js:1262:10)
    at objectAssign.fileName (/Users/Max13/Dev/OsteApp/www/node_modules/gulp-htmlmin/index.js:22:39)
    at module.exports (/Users/Max13/Dev/OsteApp/www/node_modules/tryit/tryit.js:8:9)
    at minifyHtml (/Users/Max13/Dev/OsteApp/www/node_modules/gulp-htmlmin/index.js:21:9)
    at Transform.htmlminTransform [as _transform] (/Users/Max13/Dev/OsteApp/www/node_modules/gulp-htmlmin/index.js:51:7)
    at Transform._read (/Users/Max13/Dev/OsteApp/www/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:159:10)
    at Transform._write (/Users/Max13/Dev/OsteApp/www/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_transform.js:147:83)
    at doWrite (/Users/Max13/Dev/OsteApp/www/node_modules/gulp-htmlmin/node_modules/readable-stream/lib/_stream_writable.js:319:64)
```

How can you help me? :)

**Comment by mercuryseries** [comment]
@Max13 Do you have some php into html attributes?

**Comment by Max13** [comment]
@mercuryseries Of course. The HTML forms alone need an action. Is it currently an issue ?

**Comment by mercuryseries** [comment]
@Max13 It's not an issue but sometimes some errors in your php might cause this error. 

You may try this:
1. Try to validate your html output in order to check if it is valid (https://validator.w3.org/)
2. Try to Turn off the minifyJS option.
3. Use some alternative solutions: https://github.com/fitztrev/laravel-html-minify

Let me know!

**Comment by Max13** [comment]
I've found the issue. I have a `@yield` section eclosed between `<script>` tags. And when I write a `@section` using blade, I don't open the `script` tag.

Which means, the parser is reading `javascript` in the middle of `HTML` without script tags... Of course, it can't work. I'll change my structure and see if I can take advantage of an HTML minifier
