### ISSUE TITLE
This does not work for L5.6?

### ISSUE THREAD

**Issue by rvizcaino80** [mercuryseries/laravel-elixir-minify-html#4]
Great work mate! I am trying to use this on L5.6 (mix) and I can not get it to work. I get this:

module.js:559
    throw err;
    ^

Error: Cannot find module 'laravel-elixir'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/roger/Work/Personal/ags/node_modules/laravel-elixir-minify-html/index.js:2:20)
    at Module._compile (module.js:662:30)
    at Object.Module._extensions..js (module.js:673:10)
    at Module.load (module.js:575:32)
    at tryModuleLoad (module.js:515:12)
    at Function.Module._load (module.js:507:3)

**Comment by mercuryseries** [comment]
This package is not compatible with Laravel Mix but Laravel Elixir.

**Comment by rvizcaino80** [comment]
Thanks friend!

**Comment by mercuryseries** [comment]
You're welcome.
